export const ACTION = {
    SET_LANGUAGE: 'SET_LANGUAGE',
    SET_LANGUAGE_FROM_LOCAL_STORAGE: 'SET_LANGUAGE_FROM_LOCAL_STORAGE',
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_MODAL: 'OPEN_MODAL',
    OPEN_MODAL_CONFIRM: 'OPEN_MODAL_CONFIRM',
    CLOSE_MODAL_CONFIRM: 'CLOSE_MODAL_CONFIRM',
    SET_USER_NAME: 'SET_USER_NAME',
    SET_ROUTE_PATH: 'SET_ROUTE_PATH',
    SET_CURRENT_ROUTE_FROM_SESSION_STORAGE: 'SET_CURRENT_ROUTE_FROM_SESSION_STORAGE',
}