export const ACTION = {
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LANGUAGE_FROM_LOCAL_STORAGE: 'SET_LANGUAGE_FROM_LOCAL_STORAGE',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MODAL: 'OPEN_MODAL',
  SET_ROUTE_PATH: 'SET_ROUTE_PATH',
  SET_CURRENT_ROUTE_FROM_SESSION_STORAGE:
    'SET_CURRENT_ROUTE_FROM_SESSION_STORAGE',
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  OPEN_MOBILE_MENU: 'OPEN_MOBILE_MENU',
  CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',
}
